class EzLinkData {
  static const Map<String, Map<String, String>> merchants = {
    "UOBATM": {"name": "UOB ATM", "category": "Top-up"},
    "OCBCATM": {"name": "OCBC ATM", "category": "Top-up"},
    "Mobile": {"name": "NETS FlashPay Reader App", "category": "Top-up"},
    "NTUC F": {"name": "NTUC FairPrice, Cheers", "category": "Shopping"},
    "7-ELEV": {"name": "7-Eleven", "category": "Shopping"},
    "XPRESS": {"name": "FairPrice Xpress", "category": "Top-up"},
    "CHEERS": {"name": "Cheers", "category": "Shopping"},
    "TL": {"name": "TransitLink Ticket Office", "category": "Top-up"},
    "TRANSI": {"name": "TransitLink Ticket Office", "category": "Top-up"},
    "NETS": {"name": "School canteen/bookshop", "category": "Shopping"},
    "AWESOM": {"name": "A & W", "category": "Food & Dining"},
    "SHIOK!": {"name": "Heavenly Wang", "category": "Food & Dining"},
    "TIONG": {"name": "Tiong Bahru Bakery", "category": "Food & Dining"},
    "CRYSTA": {"name": "Crystal Jade", "category": "Food & Dining"},
    "DELIFR": {"name": "Delifrance", "category": "Food & Dining"},
    "WOK EX": {"name": "NTU Wok Express", "category": "Food & Dining"},
    "GASTRO": {"name": "Maki-San", "category": "Food & Dining"},
    "Y E S": {"name": "Dian Xiao Er", "category": "Food & Dining"},
    "CREATE": {"name": "Maccha House", "category": "Food & Dining"},
    "CRAY V": {"name": "Playmade", "category": "Food & Dining"},
    "THE CO": {"name": "The Coffee Bean & Tea Leaf", "category": "Food & Dining"},
    "VISION": {"name": "Subway", "category": "Food & Dining"},
    "ABC BA": {"name": "Food and beverages", "category": "Food & Dining"},
    "BRINDA": {"name": "Food and beverages", "category": "Food & Dining"},
    "CodePackage.COMMON": {"name": "Food and beverages", "category": "Food & Dining"},
    "LOVELI": {"name": "Food and beverages", "category": "Food & Dining"},
    "KOREAN": {"name": "Food and beverages", "category": "Food & Dining"},
    "NOEL B": {"name": "Food and beverages", "category": "Food & Dining"},
    "YUMMY": {"name": "Food and beverages", "category": "Food & Dining"},
    "MALA X": {"name": "Food and beverages", "category": "Food & Dining"},
    "FISHBA": {"name": "Food and beverages", "category": "Food & Dining"},
    "YU KEE": {"name": "Yu Kee Duck Rice", "category": "Food & Dining"},
    "GODIVA": {"name": "Godiva", "category": "Food & Dining"},
    "COMPAS": {"name": "Exxonmobil ACB Canteen", "category": "Food & Dining"},
    "SINPOI": {"name": "Sinpopo", "category": "Food & Dining"},
    "UMISUS": {"name": "Umisushi", "category": "Food & Dining"},
    "LOY KE": {"name": "Loy Kee Chicken Rice", "category": "Food & Dining"},
    "MCDONA": {"name": "McDonald's", "category": "Food & Dining"},
    "HANBAO": {"name": "McDonald's", "category": "Food & Dining"},
    "KENTUC": {"name": "KFC", "category": "Food & Dining"},
    "KOUFU": {"name": "Koufu", "category": "Food & Dining"},
    "FOOD J": {"name": "Food Junction", "category": "Food & Dining"},
    "MR BEA": {"name": "Mr Bean", "category": "Food & Dining"},
    "AC HES": {"name": "llao llao", "category": "Food & Dining"},
    "BURGER": {"name": "Burger King", "category": "Food & Dining"},
    "MOS FO": {"name": "MOS Burger", "category": "Food & Dining"},
    "MOS BU": {"name": "MOS Burger", "category": "Food & Dining"},
    "GONG C": {"name": "Gong Cha", "category": "Food & Dining"},
    "V TEA": {"name": "Gong Cha", "category": "Food & Dining"},
    "BENGAW": {"name": "Bengawan Solo", "category": "Food & Dining"},
    "KOI TH": {"name": "Koi Thé", "category": "Food & Dining"},
    "KOI": {"name": "Koi Thé", "category": "Food & Dining"},
    "TEN &": {"name": "Old Chang Kee", "category": "Food & Dining"},
    "OLDCHA": {"name": "Old Chang Kee", "category": "Food & Dining"},
    "YTP": {"name": "Old Chang Kee", "category": "Food & Dining"},
    "OLD CH": {"name": "Old Chang Kee", "category": "Food & Dining"},
    "MEFTPOS": {"name": "IJOOZ vending machine, Sentosa Express, mini KTV, ActiveSG, printing, gift box etc.", "category": "Others"},
    "POLAR": {"name": "Polar Puffs and Cakes", "category": "Food & Dining"},
    "PIZZA": {"name": "Pizza Hut", "category": "Food & Dining"},
    "PEZZO": {"name": "Pezzo Pizza", "category": "Food & Dining"},
    "BREADT": {"name": "Breadtalk, Toast Box", "category": "Food & Dining"},
    "YOSHIN": {"name": "Yoshinoya", "category": "Food & Dining"},
    "JOLLIB": {"name": "Jollibean", "category": "Food & Dining"},
    "JOLLY": {"name": "Jollibean", "category": "Food & Dining"},
    "FOUR L": {"name": "Four Leaves", "category": "Food & Dining"},
    "ZENSHO": {"name": "Sukiya, Nakau, Coco's, Long John Silver etc.", "category": "Food & Dining"},
    "SUKIYA": {"name": "Sukiya", "category": "Food & Dining"},
    "YA KUN": {"name": "Ya Kun Kaya Toast", "category": "Food & Dining"},
    "JAY JA": {"name": "Ya Kun Kaya Toast", "category": "Food & Dining"},
    "TI 22": {"name": "Ya Kun Kaya Toast", "category": "Food & Dining"},
    "ZTP GI": {"name": "ZTP health products", "category": "Food & Dining"},
    "DE CHE": {"name": "Chateraise", "category": "Food & Dining"},
    "SWEE H": {"name": "Swee Heng Bakery", "category": "Food & Dining"},
    "HAN'S": {"name": "Han's", "category": "Food & Dining"},
    "HANIS": {"name": "Han's", "category": "Food & Dining"},
    "NP0031": {"name": "Marmalade Toast", "category": "Food & Dining"},
    "NPMAKA": {"name": "NP foodcourt", "category": "Food & Dining"},
    "20NTU-": {"name": "NTU foodcourt", "category": "Food & Dining"},
    "21NTU-": {"name": "NTU foodcourt", "category": "Food & Dining"},
    "34NTU": {"name": "NTU foodcourt", "category": "Food & Dining"},
    "50NTU-": {"name": "NTU foodcourt", "category": "Food & Dining"},
    "60NTU-": {"name": "NTU foodcourt", "category": "Food & Dining"},
    "NTUIFC": {"name": "NTU foodcourt", "category": "Food & Dining"},
    "NTUNSF": {"name": "NTU foodcourt", "category": "Food & Dining"},
    "NTU16": {"name": "NTU foodcourt", "category": "Food & Dining"},
    "162NTU": {"name": "NTU foodcourt", "category": "Food & Dining"},
    "32NTU-": {"name": "NTU foodcourt", "category": "Food & Dining"},
    "34NTU-": {"name": "NTU foodcourt", "category": "Food & Dining"},
    "34-NTU": {"name": "NTU foodcourt", "category": "Food & Dining"},
    "38NTU-": {"name": "NTU foodcourt", "category": "Food & Dining"},
    "NTU16-": {"name": "NTU foodcourt", "category": "Food & Dining"},
    "NTU-CN": {"name": "NTU foodcourt", "category": "Food & Dining"},
    "NTU 12": {"name": "NTU foodcourt", "category": "Food & Dining"},
    "NUSDEC": {"name": "NUS foodcourt", "category": "Food & Dining"},
    "NUSFF": {"name": "NUS foodcourt", "category": "Food & Dining"},
    "SIM-CN": {"name": "Canteen", "category": "Food & Dining"},
    "IRON C": {"name": "Canteen", "category": "Food & Dining"},
    "CHILLI": {"name": "Food Court", "category": "Food & Dining"},
    "SRI KA": {"name": "Sri Kalikamba Wines", "category": "Food & Dining"},
    "NIE-CN": {"name": "NIE foodcourt", "category": "Food & Dining"},
    "WARBUR": {"name": "Warburg vending machine", "category": "Food & Dining"},
    "BEEWOR": {"name": "Jollibee", "category": "Food & Dining"},
    "GOLDEN": {"name": "Jollibee", "category": "Food & Dining"},
    "HWEE M": {"name": "Sharetea", "category": "Food & Dining"},
    "EMPRES": {"name": "Empress Porridge", "category": "Food & Dining"},
    "ESTONI": {"name": "Mam Mam", "category": "Food & Dining"},
    "POON R": {"name": "Kaffe & Toast", "category": "Food & Dining"},
    "GALA F": {"name": "Lanzhou beef noodles etc.", "category": "Food & Dining"},
    "CRUSSH": {"name": "Crussh Acai Bowl", "category": "Food & Dining"},
    "MANNA": {"name": "Krispy Kreme", "category": "Food & Dining"},
    "FOOD R": {"name": "Food Republic", "category": "Food & Dining"},
    "SUSHIR": {"name": "Sushiro", "category": "Food & Dining"},
    "AURESYS": {"name": "Vending machine", "category": "Food & Dining"},
    "YHS (S": {"name": "Vending machine", "category": "Food & Dining"},
    "LINCO": {"name": "Vending machine", "category": "Food & Dining"},
    "SG VEN": {"name": "Vending machine", "category": "Food & Dining"},
    "PREMIE": {"name": "Vending machine", "category": "Food & Dining"},
    "ROYAL": {"name": "Vending machine", "category": "Food & Dining"},
    "SURELY": {"name": "Chinese Tofu Magician", "category": "Food & Dining"},
    "HANSFO": {"name": "Au Croissant", "category": "Food & Dining"},
    "TEA TR": {"name": "Tea Tree Cafe", "category": "Food & Dining"},
    "FOCUS": {"name": "The Cocoa Trees", "category": "Food & Dining"},
    "COLLEC": {"name": "Kopi & Tarts", "category": "Food & Dining"},
    "CHRISN": {"name": "Auntie Anne's", "category": "Food & Dining"},
    "DOWNST": {"name": "Downstairs", "category": "Food & Dining"},
    "COMPOS": {"name": "Compose Coffee", "category": "Food & Dining"},
    "GOOD D": {"name": "Good Day Cafe", "category": "Food & Dining"},
    "CTN3202": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN3205": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN3378": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN4609": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN4678": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN4720": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN4848": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN4984": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN6253": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN6275": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN7587": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN7629": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN7630": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN7636": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN7638": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN7680": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN7685": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN7686": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN7688": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN7751": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN7756": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN8191": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN8193": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN8196": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN9013": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN4586": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN6089": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN6273": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN7631": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN8260": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN8261": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN8265": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN8271": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN8272": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN8383": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN8384": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN8446": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN9042": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN7714": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN8192": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN9275": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN8198": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN8387": {"name": "Gong Cha", "category": "Food & Dining"},
    "CTN1809": {"name": "Koi", "category": "Food & Dining"},
    "CTN1813": {"name": "Koi", "category": "Food & Dining"},
    "CTN1814": {"name": "Koi", "category": "Food & Dining"},
    "CTN1823": {"name": "Koi", "category": "Food & Dining"},
    "CTN1831": {"name": "Koi", "category": "Food & Dining"},
    "CTN1836": {"name": "Koi", "category": "Food & Dining"},
    "CTN2457": {"name": "Koi", "category": "Food & Dining"},
    "CTN2516": {"name": "Koi", "category": "Food & Dining"},
    "CTN2974": {"name": "Koi", "category": "Food & Dining"},
    "CTN2979": {"name": "Koi", "category": "Food & Dining"},
    "CTN3383": {"name": "Koi", "category": "Food & Dining"},
    "CTN3681": {"name": "Koi", "category": "Food & Dining"},
    "CTN3869": {"name": "Koi", "category": "Food & Dining"},
    "CTN3870": {"name": "Koi", "category": "Food & Dining"},
    "CTN3865": {"name": "Koi", "category": "Food & Dining"},
    "CTN3871": {"name": "Koi", "category": "Food & Dining"},
    "CTN3872": {"name": "Koi", "category": "Food & Dining"},
    "CTN4545": {"name": "Koi", "category": "Food & Dining"},
    "CTN4562": {"name": "Koi", "category": "Food & Dining"},
    "CTN4654": {"name": "Koi", "category": "Food & Dining"},
    "CTN4696": {"name": "Koi", "category": "Food & Dining"},
    "CTN4857": {"name": "Koi", "category": "Food & Dining"},
    "CTN4896": {"name": "Koi", "category": "Food & Dining"},
    "CTN4978": {"name": "Koi", "category": "Food & Dining"},
    "CTN5018": {"name": "Koi", "category": "Food & Dining"},
    "CTN6194": {"name": "Koi", "category": "Food & Dining"},
    "CTN6195": {"name": "Koi", "category": "Food & Dining"},
    "CTN6241": {"name": "Koi", "category": "Food & Dining"},
    "CTN6244": {"name": "Koi", "category": "Food & Dining"},
    "CTN6245": {"name": "Koi", "category": "Food & Dining"},
    "CTN6284": {"name": "Koi", "category": "Food & Dining"},
    "CTN6352": {"name": "Koi", "category": "Food & Dining"},
    "CTN6485": {"name": "Koi", "category": "Food & Dining"},
    "CTN7125": {"name": "Koi", "category": "Food & Dining"},
    "CTN7428": {"name": "Koi", "category": "Food & Dining"},
    "CTN7588": {"name": "Koi", "category": "Food & Dining"},
    "CTN8817": {"name": "Koi", "category": "Food & Dining"},
    "CTN8901": {"name": "Koi", "category": "Food & Dining"},
    "CTN8965": {"name": "Koi", "category": "Food & Dining"},
    "CTN8918": {"name": "Koi", "category": "Food & Dining"},
    "CTN9096": {"name": "Koi", "category": "Food & Dining"},
    "CTN1824": {"name": "Koi", "category": "Food & Dining"},
    "CTN1826": {"name": "Koi", "category": "Food & Dining"},
    "CTN3105": {"name": "Koi", "category": "Food & Dining"},
    "CTN3602": {"name": "Koi", "category": "Food & Dining"},
    "CTN3693": {"name": "Koi", "category": "Food & Dining"},
    "CTN3864": {"name": "Koi", "category": "Food & Dining"},
    "CTN3873": {"name": "Koi", "category": "Food & Dining"},
    "CTN4758": {"name": "Koi", "category": "Food & Dining"},
    "CTN4855": {"name": "Koi", "category": "Food & Dining"},
    "CTN4860": {"name": "Koi", "category": "Food & Dining"},
    "CTN8264": {"name": "Koi", "category": "Food & Dining"},
    "CTN7748": {"name": "Koi", "category": "Food & Dining"},
    "CTN8923": {"name": "Koi", "category": "Food & Dining"},
    "CTN5024": {"name": "Koi", "category": "Food & Dining"},
    "CTN3194": {"name": "Koi", "category": "Food & Dining"},
    "CTN6190": {"name": "Koi", "category": "Food & Dining"},
    "CTN7740": {"name": "Koi", "category": "Food & Dining"},
    "CTN7747": {"name": "Koi", "category": "Food & Dining"},
    "CTN3090": {"name": "Koi", "category": "Food & Dining"},
    "CTN4795": {"name": "Koi", "category": "Food & Dining"},
    "CTN4843": {"name": "Koi", "category": "Food & Dining"},
    "CTN": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN0168": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN2011": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN2316": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN2398": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN2406": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN2436": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN2451": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN2489": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN2526": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN2551": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN2563": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN2594": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN2625": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN2682": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN2730": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN2734": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN2744": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN2932": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN3004": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN3147": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN3844": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN3853": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN4004": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN5187": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN6535": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN7637": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN8421": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN9313": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN9498": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN9911": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT1281": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT1354": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT1901": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT1912": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT1968": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2207": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2151": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2165": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2223": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2250": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2257": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2276": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2283": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2355": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2361": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2365": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2395": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2451": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2526": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2537": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2624": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2652": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2847": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2861": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT3177": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT3854": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT5186": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT5224": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT5239": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT1905": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2177": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2182": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2241": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2242": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2259": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2479": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2555": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2576": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2658": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2672": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2674": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2817": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT3868": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT8919": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN2231": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN2391": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN2395": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN2399": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN8547": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN6409": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN2689": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN5171": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2231": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN8919": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN2814": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN2153": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN2694": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN5249": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN6492": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN1690": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN8799": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN9162": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN9248": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN9397": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN9888": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN1425": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN7757": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN7786": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN7913": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT1700": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2263": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2309": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2524": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2581": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2810": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2844": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT5267": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN9664": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN2288": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN2363": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN2857": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN3884": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN8125": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2265": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2621": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2777": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2862": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN7203": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT2236": {"name": "Vending machine", "category": "Food & Dining"},
    "TIT8914": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN2414": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN5194": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN5236": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN7694": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN8702": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN9421": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN4600": {"name": "Cafeteria at Siemens Centre", "category": "Food & Dining"},
    "CTN9003": {"name": "Cafeteria at Siemens Centre", "category": "Food & Dining"},
    "SFIP": {"name": "Canteen", "category": "Food & Dining"},
    "CTN9009": {"name": "Canteen", "category": "Food & Dining"},
    "CTN3374": {"name": "Canteen", "category": "Food & Dining"},
    "CTN4945": {"name": "Canteen", "category": "Food & Dining"},
    "CTN6237": {"name": "Canteen", "category": "Food & Dining"},
    "CTN6326": {"name": "Canteen", "category": "Food & Dining"},
    "CTN9018": {"name": "Canteen", "category": "Food & Dining"},
    "TIT7703": {"name": "Canteen", "category": "Food & Dining"},
    "CTN2024": {"name": "Canteen", "category": "Food & Dining"},
    "CTN8362": {"name": "Canteen", "category": "Food & Dining"},
    "CTN8968": {"name": "Canteen", "category": "Food & Dining"},
    "CTN4805": {"name": "Canteen", "category": "Food & Dining"},
    "CTN9092": {"name": "Canteen", "category": "Food & Dining"},
    "CTN8248": {"name": "Canteen", "category": "Food & Dining"},
    "TIT2393": {"name": "School Canteen", "category": "Food & Dining"},
    "CTN7089": {"name": "Sapporo Petit Doughnut", "category": "Food & Dining"},
    "UCON": {"name": "Sharetea", "category": "Food & Dining"},
    "SPCL": {"name": "Spinelli Coffee", "category": "Food & Dining"},
    "CTN3110": {"name": "iTEA", "category": "Food & Dining"},
    "AV-HC": {"name": "Food and beverages", "category": "Food & Dining"},
    "CTN2283": {"name": "Food and beverages", "category": "Food & Dining"},
    "CTN2480": {"name": "Food and beverages", "category": "Food & Dining"},
    "CTN3201": {"name": "Food and beverages", "category": "Food & Dining"},
    "CTN4688": {"name": "Food and beverages", "category": "Food & Dining"},
    "CTN8230": {"name": "Food and beverages", "category": "Food & Dining"},
    "CTN8353": {"name": "Food and beverages", "category": "Food & Dining"},
    "CTN8370": {"name": "Food and beverages", "category": "Food & Dining"},
    "CTN8902": {"name": "Food and beverages", "category": "Food & Dining"},
    "CTN8976": {"name": "Food and beverages", "category": "Food & Dining"},
    "CTN9022": {"name": "Food and beverages", "category": "Food & Dining"},
    "CTN8308": {"name": "Food and beverages", "category": "Food & Dining"},
    "CTN6052": {"name": "Food and beverages", "category": "Food & Dining"},
    "TIT7701": {"name": "Murata Canteen", "category": "Food & Dining"},
    "TIT7705": {"name": "Murata Canteen", "category": "Food & Dining"},
    "TIT3065": {"name": "Murata Canteen", "category": "Food & Dining"},
    "TIT3068": {"name": "Murata Canteen", "category": "Food & Dining"},
    "TIT3070": {"name": "Murata Canteen", "category": "Food & Dining"},
    "TIT3096": {"name": "Murata Canteen", "category": "Food & Dining"},
    "TIT3102": {"name": "Murata Canteen", "category": "Food & Dining"},
    "CTN2148": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN2868": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN2509": {"name": "Vending machine", "category": "Food & Dining"},
    "CTN1864": {"name": "Vending machine", "category": "Food & Dining"},
    "HAO MA": {"name": "HAO Mart", "category": "Shopping"},
    "IROHA": {"name": "Iroha Mart", "category": "Shopping"},
    "VALUED": {"name": "ValuDollar", "category": "Shopping"},
    "INFINI": {"name": "Infinity Kpop", "category": "Shopping"},
    "GSBT": {"name": "The Grandstand", "category": "Shopping"},
    "N.U.S.": {"name": "NUS Coop", "category": "Shopping"},
    "AFTK P": {"name": "Art Friend", "category": "Shopping"},
    "PAN PA": {"name": "DON DON DONKI", "category": "Shopping"},
    "ANGEL": {"name": "Retail", "category": "Shopping"},
    "GLOBAL": {"name": "Retail", "category": "Shopping"},
    "YUE HW": {"name": "Yue Hwa Chinese Products", "category": "Shopping"},
    "UNIQLO": {"name": "Uniqlo", "category": "Shopping"},
    "METRO": {"name": "Metro", "category": "Shopping"},
    "DAISO": {"name": "Daiso", "category": "Shopping"},
    "NTUC": {"name": "NTUC FairPrice, Cheers", "category": "Shopping"},
    "GUARDI": {"name": "Guardian", "category": "Shopping"},
    "WATSON": {"name": "Watsons", "category": "Shopping"},
    "U STAR": {"name": "U-Stars Supermarket", "category": "Shopping"},
    "7SEVEN": {"name": "7-Eleven", "category": "Shopping"},
    "TAKASH": {"name": "Takashimaya", "category": "Shopping"},
    "COLD S": {"name": "Cold Storage, Giant Supermarket", "category": "Shopping"},
    "SHENG": {"name": "Sheng Siong Supermarket", "category": "Shopping"},
    "SHENGS": {"name": "Sheng Siong Supermarket", "category": "Shopping"},
    "SPH BU": {"name": "SPH Buzz", "category": "Shopping"},
    "BUZZ S": {"name": "SPH Buzz", "category": "Shopping"},
    "SHELL": {"name": "Shell Station", "category": "Shopping"},
    "POPULA": {"name": "Popular Bookstore", "category": "Shopping"},
    "KINOKU": {"name": "Kinokuniya Bookstore", "category": "Shopping"},
    "MOTHER": {"name": "Mothercare", "category": "Shopping"},
    "G2000": {"name": "G2000", "category": "Shopping"},
    "EU YAN": {"name": "Eu Yan Sang", "category": "Shopping"},
    "CHALLE": {"name": "Challenger", "category": "Shopping"},
    "TOKYU": {"name": "Tokyu Hands", "category": "Shopping"},
    "GIANT": {"name": "Giant", "category": "Shopping"},
    "ISETAN": {"name": "Isetan", "category": "Shopping"},
    "SMART9": {"name": "NTU hall minimart", "category": "Shopping"},
    "DECATH": {"name": "Decathlon", "category": "Shopping"},
    "SOL MA": {"name": "SOL Mart", "category": "Shopping"},
    "CHOPS": {"name": "Value Dollar", "category": "Shopping"},
    "PRIME": {"name": "Prime Supermarket", "category": "Shopping"},
    "MEIDI": {"name": "Meidi-ya Supermarket", "category": "Shopping"},
    "MEIDI-": {"name": "Meidi-ya Supermarket", "category": "Shopping"},
    "IKANO": {"name": "IKEA", "category": "Shopping"},
    "MOHD M": {"name": "Mustafa Centre", "category": "Shopping"},
    "CHEE": {"name": "Cheers", "category": "Shopping"},
    "CTN3025": {"name": "Cheers", "category": "Shopping"},
    "CTN3274": {"name": "Cheers", "category": "Shopping"},
    "CTN9082": {"name": "Cheers", "category": "Shopping"},
    "CTN9173": {"name": "Cheers", "category": "Shopping"},
    "CTN2915": {"name": "Cheers", "category": "Shopping"},
    "CTN2987": {"name": "Cheers", "category": "Shopping"},
    "CTN3157": {"name": "Cheers", "category": "Shopping"},
    "CTN3198": {"name": "Cheers", "category": "Shopping"},
    "CTN8484": {"name": "Cheers", "category": "Shopping"},
    "CTN8891": {"name": "Cheers", "category": "Shopping"},
    "CTN6546": {"name": "Cheers", "category": "Shopping"},
    "CTN8359": {"name": "Cheers", "category": "Shopping"},
    "CTN3160": {"name": "Cheers", "category": "Shopping"},
    "CTN2953": {"name": "Cheers", "category": "Shopping"},
    "CTN8275": {"name": "Cheers", "category": "Shopping"},
    "CTN8361": {"name": "Cheers", "category": "Shopping"},
    "CTN3397": {"name": "Cheers", "category": "Shopping"},
    "CTN8890": {"name": "Cheers", "category": "Shopping"},
    "CTN3347": {"name": "Bookstore", "category": "Shopping"},
    "CTN3349": {"name": "Bookstore", "category": "Shopping"},
    "CTN6118": {"name": "Bookstore", "category": "Shopping"},
    "CTN6163": {"name": "Bookstore", "category": "Shopping"},
    "CTN6251": {"name": "Bookstore", "category": "Shopping"},
    "CTN6296": {"name": "Bookstore", "category": "Shopping"},
    "CTN8984": {"name": "Bookstore", "category": "Shopping"},
    "CTN3081": {"name": "Bookstore", "category": "Shopping"},
    "CTN6082": {"name": "Bookstore", "category": "Shopping"},
    "CTN6174": {"name": "Bookstore", "category": "Shopping"},
    "CTN6327": {"name": "Bookstore", "category": "Shopping"},
    "711S": {"name": "7-Eleven", "category": "Shopping"},
    "ShareTarget.METHOD_POST": {"name": "7-Eleven", "category": "Shopping"},
    "SV11": {"name": "7-Eleven", "category": "Shopping"},
    "CTN3284": {"name": "7-Eleven", "category": "Shopping"},
    "CTN3290": {"name": "7-Eleven", "category": "Shopping"},
    "CTN3301": {"name": "7-Eleven", "category": "Shopping"},
    "CTN4782": {"name": "7-Eleven", "category": "Shopping"},
    "TIT2800": {"name": "7-Eleven", "category": "Shopping"},
    "CTN8306": {"name": "7-Eleven", "category": "Shopping"},
    "CTN8249": {"name": "7-Eleven", "category": "Shopping"},
    "CTN7765": {"name": "7-Eleven", "category": "Shopping"},
    "CTN3310": {"name": "7-Eleven", "category": "Shopping"},
    "CTN6356": {"name": "7-Eleven", "category": "Shopping"},
    "CTN3292": {"name": "7-Eleven", "category": "Shopping"},
    "CTN3345": {"name": "7-Eleven", "category": "Shopping"},
    "CTN9508": {"name": "7-Eleven", "category": "Shopping"},
    "CTN4601": {"name": "7-Eleven", "category": "Shopping"},
    "CTN5009": {"name": "7-Eleven", "category": "Shopping"},
    "CTN6081": {"name": "7-Eleven", "category": "Shopping"},
    "CTN3295": {"name": "7-Eleven", "category": "Shopping"},
    "CTN8481": {"name": "7-Eleven", "category": "Shopping"},
    "CTN9046": {"name": "7-Eleven", "category": "Shopping"},
    "CTN9373": {"name": "7-Eleven", "category": "Shopping"},
    "CTN8979": {"name": "7-Eleven", "category": "Shopping"},
    "CTN7583": {"name": "7-Eleven", "category": "Shopping"},
    "CTN3192": {"name": "7-Eleven", "category": "Shopping"},
    "CTN4576": {"name": "7-Eleven", "category": "Shopping"},
    "CTN4779": {"name": "7-Eleven", "category": "Shopping"},
    "CTN4890": {"name": "7-Eleven", "category": "Shopping"},
    "CTN7715": {"name": "7-Eleven", "category": "Shopping"},
    "CTN9023": {"name": "7-Eleven", "category": "Shopping"},
    "CTN9270": {"name": "7-Eleven", "category": "Shopping"},
    "CTN9278": {"name": "7-Eleven", "category": "Shopping"},
    "CTN4765": {"name": "7-Eleven", "category": "Shopping"},
    "CTN4931": {"name": "7-Eleven", "category": "Shopping"},
    "CTN4987": {"name": "7-Eleven", "category": "Shopping"},
    "CTN6064": {"name": "7-Eleven", "category": "Shopping"},
    "CTN7607": {"name": "7-Eleven", "category": "Shopping"},
    "CTN6115": {"name": "7-Eleven", "category": "Shopping"},
    "CTN9227": {"name": "7-Eleven", "category": "Shopping"},
    "CTN3416": {"name": "7-Eleven", "category": "Shopping"},
    "CTN4769": {"name": "7-Eleven", "category": "Shopping"},
    "CTN4777": {"name": "7-Eleven", "category": "Shopping"},
    "CTN4863": {"name": "7-Eleven", "category": "Shopping"},
    "CTN6085": {"name": "7-Eleven", "category": "Shopping"},
    "CTN6192": {"name": "7-Eleven", "category": "Shopping"},
    "CTN8222": {"name": "7-Eleven", "category": "Shopping"},
    "CTN8793": {"name": "7-Eleven", "category": "Shopping"},
    "CTN8788": {"name": "7-Eleven", "category": "Shopping"},
    "CTN8915": {"name": "7-Eleven", "category": "Shopping"},
    "CTN9207": {"name": "7-Eleven", "category": "Shopping"},
    "CTN9273": {"name": "7-Eleven", "category": "Shopping"},
    "CTN9241": {"name": "7-Eleven", "category": "Shopping"},
    "CTN9431": {"name": "7-Eleven", "category": "Shopping"},
    "CTN9266": {"name": "7-Eleven", "category": "Shopping"},
    "COLD": {"name": "Cold Storage", "category": "Shopping"},
    "GIAN": {"name": "Giant", "category": "Shopping"},
    "GUAR": {"name": "Guardian", "category": "Shopping"},
    "CTN3850": {"name": "District 5", "category": "Shopping"},
    "CTN3330": {"name": "SPH Buzz", "category": "Shopping"},
    "CTN8997": {"name": "SPH Buzz", "category": "Shopping"},
    "CTN8995": {"name": "SPH Buzz", "category": "Shopping"},
    "CTN8395": {"name": "SPH Buzz", "category": "Shopping"},
    "CTN2880": {"name": "SPH Buzz", "category": "Shopping"},
    "CTN5216": {"name": "SPH Buzz", "category": "Shopping"},
    "CTN2928": {"name": "SPH Buzz", "category": "Shopping"},
    "CTN7613": {"name": "SPH Buzz", "category": "Shopping"},
    "CTN2219": {"name": "Retail", "category": "Shopping"},
    "CTN7290": {"name": "Retail", "category": "Shopping"},
    "CTN9381": {"name": "Retail", "category": "Shopping"},
    "CTN2945": {"name": "Retail", "category": "Shopping"},
    "CTN3243": {"name": "Retail", "category": "Shopping"},
    "CTN6277": {"name": "Retail", "category": "Shopping"},
    "CTN3367": {"name": "Retail", "category": "Shopping"},
    "CTN8346": {"name": "Retail", "category": "Shopping"},
    "TWOK": {"name": "Roche", "category": "Shopping"},
    "BPSV09": {"name": "Zoo Shuttle Bus Service", "category": "Others"},
    "BPSV10": {"name": "Zoo Shuttle Bus Service", "category": "Others"},
    "BPSV12": {"name": "Zoo Shuttle Bus Service", "category": "Others"},
    "SENT": {"name": "Sentosa Express", "category": "Others"},
    "NERAME": {"name": "Jurong Island Bus Service", "category": "Others"},
    "COMMUT": {"name": "Premium bus service", "category": "Others"},
    "NP0052": {"name": "Premium bus service", "category": "Others"},
    "NP0118": {"name": "Premium bus service", "category": "Others"},
    "NP0125": {"name": "Premium bus service", "category": "Others"},
    "NP0100": {"name": "Condo shuttle bus service", "category": "Others"},
    "NP0111": {"name": "Causeway Link Bus Service", "category": "Others"},
    "NP0136": {"name": "Causeway Link Bus Service", "category": "Others"},
    "NP0142": {"name": "Causeway Link Bus Service", "category": "Others"},
    "NP0150": {"name": "Causeway Link Bus Service", "category": "Others"},
    "NP0108": {"name": "Causeway Link Bus Service", "category": "Others"},
    "NP0147": {"name": "Causeway Link Bus Service", "category": "Others"},
    "NP0187": {"name": "Causeway Link Bus Service", "category": "Others"},
    "NP0122": {"name": "Resort World Sentosa Bus Service RWS8", "category": "Others"},
    "COMFORT": {"name": "Taxi, diesel & petro kiosk etc", "category": "Others"},
    "TIT7613": {"name": "Transtar bus service", "category": "Others"},
    "TIT8895": {"name": "IBP shuttle bus", "category": "Others"},
    "TIT8957": {"name": "IBP shuttle bus", "category": "Others"},
    "TIT8961": {"name": "IBP shuttle bus", "category": "Others"},
    "TAXI": {"name": "Taxi", "category": "Others"},
    "COMFOR": {"name": "Taxi", "category": "Others"},
    "CTXI": {"name": "Taxi", "category": "Others"},
    "CTN8765": {"name": "Taxi", "category": "Others"},
    "TIT4830": {"name": "Premium Bus Service", "category": "Others"},
    "TIT4954": {"name": "Premium Bus Service", "category": "Others"},
    "TIT5010": {"name": "Premium Bus Service", "category": "Others"},
    "TIT9066": {"name": "Premium Bus Service", "category": "Others"},
    "TIT9104": {"name": "Premium Bus Service", "category": "Others"},
    "TIT4591": {"name": "Premium Bus Service", "category": "Others"},
    "TIT4854": {"name": "Premium Bus Service", "category": "Others"},
    "TIT4861": {"name": "Premium Bus Service", "category": "Others"},
    "TIT4886": {"name": "Premium Bus Service", "category": "Others"},
    "TIT4907": {"name": "Premium Bus Service", "category": "Others"},
    "TIT8946": {"name": "Premium Bus Service", "category": "Others"},
    "TIT8990": {"name": "Premium Bus Service", "category": "Others"},
    "TIT9091": {"name": "Premium Bus Service", "category": "Others"},
    "TIT4544": {"name": "Premium Bus Service", "category": "Others"},
    "TIT5021": {"name": "Premium Bus Service", "category": "Others"},
    "TIT6100": {"name": "Premium Bus Service", "category": "Others"},
    "TIT8286": {"name": "Premium Bus Service", "category": "Others"},
    "TIT8373": {"name": "Premium Bus Service", "category": "Others"},
    "TIT8778": {"name": "Premium Bus Service", "category": "Others"},
    "TIT8804": {"name": "Premium Bus Service", "category": "Others"},
    "TIT8933": {"name": "Premium Bus Service", "category": "Others"},
    "TIT8938": {"name": "Premium Bus Service", "category": "Others"},
    "AC": {"name": "Advanced Coach Bus Service", "category": "Others"},
    "CTN8749": {"name": "Premium bus service", "category": "Others"},
    "TIT4593": {"name": "Premium bus service", "category": "Others"},
    "CTN8914": {"name": "Naik Bus", "category": "Others"},
    "CTN8748": {"name": "Sentosa Cove Bus", "category": "Others"},
    "TIT4605": {"name": "Zoo Shuttle Bus Service", "category": "Others"},
    "TIT8217": {"name": "Smart bus", "category": "Others"},
    "TIT8905": {"name": "one-north Rider", "category": "Others"},
    "TIT8936": {"name": "Cross-border Bus Service", "category": "Others"},
    "TIT8848": {"name": "Cross-border Bus Service", "category": "Others"},
    "TIT8988": {"name": "Cross-border Bus Service", "category": "Others"},
    "TIT4793": {"name": "Cross-border Bus Service", "category": "Others"},
    "TIT4939": {"name": "Zoo Shuttle Bus", "category": "Others"},
    "TIT6353": {"name": "Zoo Shuttle Bus", "category": "Others"},
    "TIT8527": {"name": "Zoo Shuttle Bus", "category": "Others"},
    "TIT8284": {"name": "Zoo Shuttle Bus", "category": "Others"},
    "TIT8522": {"name": "Zoo Shuttle Bus", "category": "Others"},
    "TIT8470": {"name": "myBus Bus Service", "category": "Others"},
    "TIT8999": {"name": "myBus Bus Service", "category": "Others"},
    "TIT8836": {"name": "Elias Green Shuttle Bus Service", "category": "Others"},
    "43ASTL": {"name": "Jurong Island Bus Service", "category": "Others"},
    "TOG CO": {"name": "Toy Or Game", "category": "Leisure"},
    "GARDEN": {"name": "Garden by the Bay", "category": "Leisure"},
    "CATHAY": {"name": "Cathay Cineplex", "category": "Leisure"},
    "SNSA02": {"name": "SAFRA", "category": "Leisure"},
    "JESC08": {"name": "Swimming complex ticket", "category": "Leisure"},
    "WOSC01": {"name": "Swimming complex ticket", "category": "Leisure"},
    "WOSC06": {"name": "Swimming complex ticket", "category": "Leisure"},
    "CSPR01": {"name": "Swimming complex ticket", "category": "Leisure"},
    "SKSC11": {"name": "Swimming complex ticket", "category": "Leisure"},
    "SPPL15": {"name": "Singapore Pools", "category": "Leisure"},
    "SPPL38": {"name": "Singapore Pools", "category": "Leisure"},
    "SPPL53": {"name": "Singapore Pools", "category": "Leisure"},
    "SPPL19": {"name": "Singapore Pools", "category": "Leisure"},
    "S.POOL": {"name": "Singapore Pools", "category": "Leisure"},
    "TIMEZO": {"name": "Timezone Games", "category": "Leisure"},
    "TURF": {"name": "Singapore Turf Club", "category": "Leisure"},
    "SSCN": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN1711": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN1791": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN7218": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN7737": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "TIT8805": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "TIT9032": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "TIT9044": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "TIT9046": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "TIT9053": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "TIT9056": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "TIT9057": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "TIT9068": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "TIT9076": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "TIT9078": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "TIT9079": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "TIT9085": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "TIT9087": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "TIT9111": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "TIT9114": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "TIT9115": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "TIT9118": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "TIT9121": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "TIT9122": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "TIT9123": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "TIT9125": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "TIT9127": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN0020": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN0143": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN0163": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN0165": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN2653": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN2916": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN2954": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN3026": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN7093": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN7387": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN7390": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN7394": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN7687": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN7698": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN7700": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN9932": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN9940": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN9971": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "TIT6009": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN7682": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN0167": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN0247": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN7727": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN2525": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN1694": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN1719": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN4014": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN4267": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN6009": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN7697": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN7733": {"name": "ActiveSG Swimming complex ticket", "category": "Leisure"},
    "CTN1797": {"name": "ActiveSG", "category": "Leisure"},
    "CTN6103": {"name": "ActiveSG", "category": "Leisure"},
    "TIT4704": {"name": "ActiveSG", "category": "Leisure"},
    "TIT9048": {"name": "ActiveSG", "category": "Leisure"},
    "CTN0242": {"name": "ActiveSG", "category": "Leisure"},
    "CTN3311": {"name": "ActiveSG", "category": "Leisure"},
    "VRST": {"name": "Singapore Pools Betting Centre", "category": "Leisure"},
    "INGENI": {"name": "Shuttle bus service, premium bus service, canteen etc.", "category": "Others"},
    "SINGHE": {"name": "SingHealth Hospital/Polyclinics/HPB", "category": "Others"},
    "HEALTH": {"name": "SingHealth Hospital/Polyclinics/HPB", "category": "Others"},
    "NATION": {"name": "SingHealth Hospital/Polyclinics/HPB", "category": "Others"},
    "SENG": {"name": "Printing", "category": "Others"},
    "CSPL08": {"name": "Printing", "category": "Others"},
    "USPP12": {"name": "Printing", "category": "Others"},
    "USPP15": {"name": "Printing", "category": "Others"},
    "USPP21": {"name": "Printing", "category": "Others"},
    "USPP30": {"name": "Printing", "category": "Others"},
    "CSPL23": {"name": "Printing", "category": "Others"},
    "CSPL36": {"name": "Printing", "category": "Others"},
    "Y49L/Y": {"name": "Parking fee", "category": "Others"},
    "ZRX": {"name": "Parking fee", "category": "Others"},
    "GOLDVE": {"name": "Parking fee", "category": "Others"},
    "TAN TO": {"name": "Parking fee", "category": "Others"},
    "ST ELE": {"name": "Parking fee", "category": "Others"},
    "SAF WA": {"name": "Parking fee", "category": "Others"},
    "ROBERT": {"name": "Parking fee", "category": "Others"},
    "RAMKY": {"name": "Parking fee", "category": "Others"},
    "PEACE": {"name": "Parking fee", "category": "Others"},
    "NUH": {"name": "Parking fee", "category": "Others"},
    "NTUC C": {"name": "Parking fee", "category": "Others"},
    "JACK I": {"name": "Parking fee", "category": "Others"},
    "8 CROS": {"name": "Parking fee", "category": "Others"},
    "CEL PR": {"name": "Parking fee", "category": "Others"},
    "HSBC I": {"name": "Parking fee", "category": "Others"},
    "G TECH": {"name": "Parking fee", "category": "Others"},
    "LHNPAR": {"name": "Parking fee", "category": "Others"},
    "THE MC": {"name": "Parking fee", "category": "Others"},
    "WILSON": {"name": "Parking fee", "category": "Others"},
    "CHANGI": {"name": "Parking fee", "category": "Others"},
    "DARMON": {"name": "Parking fee", "category": "Others"},
    "KIANAN": {"name": "Parking fee", "category": "Others"},
    "KK WOM": {"name": "Parking fee", "category": "Others"},
    "SAND S": {"name": "Parking fee", "category": "Others"},
    "SCOTTS": {"name": "Parking fee", "category": "Others"},
    "TOPPAR": {"name": "Parking fee", "category": "Others"},
    "THEMCS": {"name": "Parking fee", "category": "Others"},
    "MP3551": {"name": "Parking fee", "category": "Others"},
    "OGPTEL": {"name": "Parking fee", "category": "Others"},
    "PRSK01": {"name": "Parking fee", "category": "Others"},
    "HIAPHU": {"name": "Parking fee", "category": "Others"},
    "AHPZ01": {"name": "Parking fee", "category": "Others"},
    "HSBCIN": {"name": "Parking fee", "category": "Others"},
    "SECURE": {"name": "Parking fee", "category": "Others"},
    "SI1": {"name": "Parking fee", "category": "Others"},
    "SI": {"name": "Parking fee", "category": "Others"},
    "TSKM01": {"name": "Parking fee", "category": "Others"},
    "AFSR01": {"name": "Parking fee", "category": "Others"},
    "CHYE L": {"name": "Parking fee", "category": "Others"},
    "DBS TR": {"name": "Parking fee", "category": "Others"},
    "EU TON": {"name": "Parking fee", "category": "Others"},
    "LHN PA": {"name": "Parking fee", "category": "Others"},
    "P PARK": {"name": "Parking fee", "category": "Others"},
    "SENTOS": {"name": "Parking fee", "category": "Others"},
    "PAYMEN": {"name": "Library payment, Sentosa Express, printing etc", "category": "Others"},
    "QBHS": {"name": "QB House", "category": "Others"},
    "STORHU": {"name": "StorHub self storage", "category": "Others"},
    "COPIER": {"name": "Photocopying", "category": "Others"},
    "USPP24": {"name": "Printing", "category": "Others"},
    "SENG81": {"name": "Printing", "category": "Others"},
    "USPP35": {"name": "Photocopying", "category": "Others"},
    "CARDTE": {"name": "Premium bus service, cafe etc.", "category": "Others"},
    "JASONS": {"name": "JasonSally Hairdressers", "category": "Others"},
    "CSPL30": {"name": "Printing", "category": "Others"},
    "CSPL34": {"name": "Campus supplies, printing etc", "category": "Others"},
    "CSPL22": {"name": "Campus supplies, printing etc", "category": "Others"},
    "SINGAP": {"name": "Singapore Pools, SAM kiosk payment, parking fees", "category": "Others"},
    "REPUBL": {"name": "Republic Polytechnic", "category": "Others"},
    "MACH P": {"name": "FotoHub", "category": "Others"},
    "TOP PA": {"name": "Parking fee", "category": "Others"},
    "CASTLE": {"name": "Vending machine, canteen, shuttle bus, taxi, printing etc", "category": "Others"},
    "CTN1654": {"name": "Library payment", "category": "Others"},
    "CTN2291": {"name": "Library payment", "category": "Others"},
    "CTN9584": {"name": "Library payment", "category": "Others"},
    "CTN1578": {"name": "Library payment", "category": "Others"},
    "CTN2027": {"name": "Library payment", "category": "Others"},
    "CTN2090": {"name": "Library payment", "category": "Others"},
    "CTN2419": {"name": "Library payment", "category": "Others"},
    "CTN2488": {"name": "Library payment", "category": "Others"},
    "CTN3010": {"name": "Library payment", "category": "Others"},
    "CTN3065": {"name": "Library payment", "category": "Others"},
    "CTN3338": {"name": "Library payment", "category": "Others"},
    "CTN5361": {"name": "Library payment", "category": "Others"},
    "CTN5482": {"name": "Library payment", "category": "Others"},
    "CTN5532": {"name": "Library payment", "category": "Others"},
    "CTN5705": {"name": "Library payment", "category": "Others"},
    "CTN6022": {"name": "Library payment", "category": "Others"},
    "CTN8998": {"name": "Library payment", "category": "Others"},
    "CTN9642": {"name": "Library payment", "category": "Others"},
    "CTN1582": {"name": "Library payment", "category": "Others"},
    "CTN2780": {"name": "Library payment", "category": "Others"},
    "CTN2835": {"name": "Library payment", "category": "Others"},
    "CTN3283": {"name": "Library payment", "category": "Others"},
    "CTN5952": {"name": "Library payment", "category": "Others"},
    "CTN5431": {"name": "Library payment", "category": "Others"},
    "CTN5550": {"name": "Library payment", "category": "Others"},
    "CTN5566": {"name": "Library payment", "category": "Others"},
    "CTN2631": {"name": "Library payment", "category": "Others"},
    "CTN4226": {"name": "Library payment", "category": "Others"},
    "CTN2217": {"name": "Library payment", "category": "Others"},
    "CTN2320": {"name": "Library payment", "category": "Others"},
    "CTN1522": {"name": "Library payment", "category": "Others"},
    "CTN2322": {"name": "Library payment", "category": "Others"},
    "CTN2461": {"name": "Library payment", "category": "Others"},
    "TIT2489": {"name": "Library payment", "category": "Others"},
    "CTN2761": {"name": "Library payment", "category": "Others"},
    "CTN1998": {"name": "Library payment", "category": "Others"},
    "CTN2961": {"name": "Library payment", "category": "Others"},
    "CTN3034": {"name": "Library payment", "category": "Others"},
    "CTN2818": {"name": "Library payment", "category": "Others"},
    "CTN5543": {"name": "Library payment", "category": "Others"},
    "CTN6042": {"name": "Library payment", "category": "Others"},
    "CTN5795": {"name": "Library payment", "category": "Others"},
    "CTN6002": {"name": "Library payment", "category": "Others"},
    "CTN4847": {"name": "Library payment", "category": "Others"},
    "CTN2455": {"name": "Library payment", "category": "Others"},
    "CTN3257": {"name": "Library payment", "category": "Others"},
    "CTN2034": {"name": "Library payment", "category": "Others"},
    "CTN9731": {"name": "Library payment", "category": "Others"},
    "QBSE": {"name": "QB House", "category": "Others"},
    "QBSE10": {"name": "QB House", "category": "Others"},
    "USPP": {"name": "Printing", "category": "Others"},
    "CSPL": {"name": "Printing", "category": "Others"},
    "CTN2374": {"name": "Printing", "category": "Others"},
    "CTN2511": {"name": "Printing", "category": "Others"},
    "CTN9590": {"name": "Printing", "category": "Others"},
    "TIT2807": {"name": "Printing", "category": "Others"},
    "TIT5193": {"name": "Printing", "category": "Others"},
    "CTN3303": {"name": "Printing", "category": "Others"},
    "EAZI": {"name": "Printing", "category": "Others"},
    "NERA": {"name": "McDonald's, KFC, food court, canteen, Decathlon, shuttle bus services, library fines, locker etc.", "category": "Others"},
    "CTN0001": {"name": "Swimming pool ticket, zoo shuttle bus etc.", "category": "Others"},
    "PPOW": {"name": "Laundry", "category": "Others"},
    "CTN4893": {"name": "Laundry", "category": "Others"},
    "CTN3382": {"name": "Medical consultation", "category": "Others"},
    "ICAS": {"name": "Immigration & Checkpoints Authority of Singapore", "category": "Others"},
    "CTN4669": {"name": "Immigration & Checkpoints Authority of Singapore", "category": "Others"},
    "CTN7604": {"name": "Community Club", "category": "Others"},
    "STEL": {"name": "Public phone", "category": "Others"},
    "AURESY": {"name": "Printing, vending machine, canteen, shuttle services etc", "category": "Others"},
    "EZL EIR": {"name": "EZ-Link card deduction", "category": "Others"},
  };

  static const Map<String, Map<String, String>> stations = {
    "JUR": {"code": "EW24", "name": "Jurong East"},
    "BBT": {"code": "NS2", "name": "Bukit Batok"},
    "BGB": {"code": "NS3", "name": "Bukit Gombak"},
    "CCK": {"code": "NS4", "name": "Choa Chu Kang"},
    "YWT": {"code": "NS5", "name": "Yew Tee"},
    "KRJ": {"code": "NS7", "name": "Kranji"},
    "MSL": {"code": "NS8", "name": "Marsiling"},
    "WDL": {"code": "NS9", "name": "Woodlands"},
    "ADM": {"code": "NS10", "name": "Admiralty"},
    "SBW": {"code": "NS11", "name": "Sembawang"},
    "CBR": {"code": "NS12", "name": "Canberra"},
    "YIS": {"code": "NS13", "name": "Yishun"},
    "KTB": {"code": "NS14", "name": "Khatib"},
    "YCK": {"code": "NS15", "name": "Yio Chu Kang"},
    "AMK": {"code": "NS16", "name": "Ang Mo Kio"},
    "BSH": {"code": "NS17", "name": "Bishan"},
    "BDL": {"code": "NS18", "name": "Braddell"},
    "TAP": {"code": "NS19", "name": "Toa Payoh"},
    "NOV": {"code": "NS20", "name": "Novena"},
    "NEW": {"code": "NS21", "name": "Newton"},
    "ORC": {"code": "NS22", "name": "Orchard"},
    "SOM": {"code": "NS23", "name": "Somerset"},
    "DBG": {"code": "NS24", "name": "Dhoby Ghaut"},
    "CTH": {"code": "EW13", "name": "City Hall"},
    "RFP": {"code": "EW14", "name": "Raffles Place"},
    "MRB": {"code": "NS27", "name": "Marina Bay"},
    "MSP": {"code": "NS28", "name": "Marina South Pier"},
    "PSR": {"code": "EW1", "name": "Pasir Ris"},
    "TAM": {"code": "EW2", "name": "Tampines"},
    "SIM": {"code": "EW3", "name": "Simei"},
    "TNM": {"code": "EW4", "name": "Tanah Merah"},
    "BDK": {"code": "EW5", "name": "Bedok"},
    "KEM": {"code": "EW6", "name": "Kembangan"},
    "EUN": {"code": "EW7", "name": "Eunos"},
    "PYL": {"code": "EW8", "name": "Paya Lebar"},
    "ALJ": {"code": "EW9", "name": "Aljunied"},
    "KAL": {"code": "EW10", "name": "Kallang"},
    "LVR": {"code": "EW11", "name": "Lavender"},
    "BGS": {"code": "EW12", "name": "Bugis"},
    "TPG": {"code": "EW15", "name": "Tanjong Pagar"},
    "OTP": {"code": "EW16", "name": "Outram Park"},
    "TIB": {"code": "EW17", "name": "Tiong Bahru"},
    "RDH": {"code": "EW18", "name": "Redhill"},
    "QUE": {"code": "EW19", "name": "Queenstown"},
    "COM": {"code": "EW20", "name": "Commonwealth"},
    "BNV": {"code": "EW21", "name": "Buona Vista"},
    "DVR": {"code": "EW22", "name": "Dover"},
    "CLE": {"code": "EW23", "name": "Clementi"},
    "CNG": {"code": "EW25", "name": "Chinese Garden"},
    "LKS": {"code": "EW26", "name": "Lakeside"},
    "BNL": {"code": "EW27", "name": "Boon Lay"},
    "PNR": {"code": "EW28", "name": "Pioneer"},
    "JKN": {"code": "EW29", "name": "Joo Koon"},
    "GCL": {"code": "EW30", "name": "Gul Circle"},
    "TCR": {"code": "EW31", "name": "Tuas Crescent"},
    "TWR": {"code": "EW32", "name": "Tuas West Road"},
    "TLK": {"code": "EW33", "name": "Tuas Link"},
    "XPO": {"code": "CG1", "name": "Expo"},
    "CGA": {"code": "CG2", "name": "Changi Airport"},
    "HBF": {"code": "NE1", "name": "HarbourFront"},
    "OTN": {"code": "NE3", "name": "Outram Park"},
    "CNT": {"code": "NE4", "name": "Chinatown"},
    "CQY": {"code": "NE5", "name": "Clarke Quay"},
    "DBN": {"code": "CC1", "name": "Dhoby Ghaut"},
    "LTI": {"code": "NE7", "name": "Little India"},
    "FRP": {"code": "NE8", "name": "Farrer Park"},
    "BNK": {"code": "NE9", "name": "Boon Keng"},
    "PTP": {"code": "NE10", "name": "Potong Pasir"},
    "WLH": {"code": "NE11", "name": "Woodleigh"},
    "SER": {"code": "NE12", "name": "Serangoon"},
    "KVN": {"code": "NE13", "name": "Kovan"},
    "HGN": {"code": "NE14", "name": "Hougang"},
    "BGK": {"code": "NE15", "name": "Buangkok"},
    "SKG": {"code": "NE16", "name": "Sengkang"},
    "PGL": {"code": "NE17", "name": "Punggol"},
    "PGC": {"code": "NE18", "name": "Punggol Coast"},
    "BBS": {"code": "CC2", "name": "Bras Basah"},
    "EPN": {"code": "CC3", "name": "Esplanade"},
    "PMN": {"code": "CC4", "name": "Promenade"},
    "NCH": {"code": "CC5", "name": "Nicoll Highway"},
    "SDM": {"code": "CC6", "name": "Stadium"},
    "MBT": {"code": "CC7", "name": "Mountbatten"},
    "DKT": {"code": "CC8", "name": "Dakota"},
    "PLC": {"code": "CC9", "name": "Paya Lebar"},
    "MPS": {"code": "CC10", "name": "MacPherson"},
    "TSG": {"code": "CC11", "name": "Tai Seng"},
    "BLY": {"code": "CC12", "name": "Bartley"},
    "SRC": {"code": "CC13", "name": "Serangoon"},
    "LRC": {"code": "CC14", "name": "Lorong Chuan"},
    "BHC": {"code": "CC15", "name": "Bishan"},
    "MRM": {"code": "CC16", "name": "Marymount"},
    "CDT": {"code": "CC17", "name": "Caldecott"},
    "BTN": {"code": "CC19", "name": "Botanic Gardens"},
    "FRR": {"code": "CC20", "name": "Farrer Road"},
    "HLV": {"code": "CC21", "name": "Holland Village"},
    "BNC": {"code": "CC22", "name": "Buona Vista"},
    "BVC": {"code": "CC22", "name": "Buona Vista"},
    "ONH": {"code": "CC23", "name": "one-north"},
    "KRG": {"code": "CC24", "name": "Kent Ridge"},
    "HPV": {"code": "CC25", "name": "Haw Par Villa"},
    "PPJ": {"code": "CC26", "name": "Pasir Panjang"},
    "LBD": {"code": "CC27", "name": "Labrador Park"},
    "TLB": {"code": "CC28", "name": "Telok Blangah"},
    "HBC": {"code": "CC29", "name": "HarbourFront"},
    "HFC": {"code": "CC29", "name": "HarbourFront"},
    "BFT": {"code": "CE1", "name": "Bayfront"},
    "MRC": {"code": "CE2", "name": "Marina Bay"},
    "BPJ": {"code": "DT1", "name": "Bukit Panjang"},
    "CSW": {"code": "DT2", "name": "Cashew"},
    "HVW": {"code": "DT3", "name": "Hillview"},
    "HUM": {"code": "DT4", "name": "Hume"},
    "BTW": {"code": "DT5", "name": "Beauty World"},
    "KAP": {"code": "DT6", "name": "King Albert Park"},
    "SAV": {"code": "DT7", "name": "Sixth Avenue"},
    "TKK": {"code": "DT8", "name": "Tan Kah Kee"},
    "BTD": {"code": "DT9", "name": "Botanic Gardens"},
    "SVS": {"code": "DT10", "name": "Stevens"},
    "STV": {"code": "DT10", "name": "Stevens"},
    "NTD": {"code": "DT11", "name": "Newton"},
    "LTD": {"code": "DT12", "name": "Little India"},
    "RCR": {"code": "DT13", "name": "Rochor"},
    "BGD": {"code": "DT14", "name": "Bugis"},
    "BFD": {"code": "DT16", "name": "Bayfront"},
    "DTN": {"code": "DT17", "name": "Downtown"},
    "TLA": {"code": "DT18", "name": "Telok Ayer"},
    "CND": {"code": "DT19", "name": "Chinatown"},
    "FCN": {"code": "DT20", "name": "Fort Canning"},
    "BCN": {"code": "DT21", "name": "Bencoolen"},
    "BCL": {"code": "DT21", "name": "Bencoolen"},
    "JLB": {"code": "DT22", "name": "Jalan Besar"},
    "BDM": {"code": "DT23", "name": "Bendemeer"},
    "GLB": {"code": "DT24", "name": "Geylang Bahru"},
    "MTR": {"code": "DT25", "name": "Mattar"},
    "MPD": {"code": "DT26", "name": "MacPherson"},
    "UBI": {"code": "DT27", "name": "Ubi"},
    "KKB": {"code": "DT28", "name": "Kaki Bukit"},
    "BDN": {"code": "DT29", "name": "Bedok North"},
    "BDR": {"code": "DT30", "name": "Bedok Reservoir"},
    "TPW": {"code": "DT31", "name": "Tampines West"},
    "TPC": {"code": "DT32", "name": "Tampines"},
    "TPE": {"code": "DT33", "name": "Tampines East"},
    "UPC": {"code": "DT34", "name": "Upper Changi"},
    "XPD": {"code": "DT35", "name": "Expo"},
    "WDN": {"code": "TE1", "name": "Woodlands North"},
    "WDT": {"code": "TE2", "name": "Woodlands"},
    "WDS": {"code": "TE3", "name": "Woodlands South"},
    "SPL": {"code": "TE4", "name": "Springleaf"},
    "LTR": {"code": "TE5", "name": "Lentor"},
    "MFL": {"code": "TE6", "name": "Mayflower"},
    "BRH": {"code": "TE7", "name": "Bright Hill"},
    "UTS": {"code": "TE8", "name": "Upper Thomson"},
    "CDE": {"code": "TE9", "name": "Caldecott"},
    "STT": {"code": "TE11", "name": "Stevens"},
    "NPR": {"code": "TE12", "name": "Napier"},
    "OBV": {"code": "TE13", "name": "Orchard Boulevard"},
    "ORT": {"code": "TE14", "name": "Orchard"},
    "GRW": {"code": "TE15", "name": "Great World"},
    "HVL": {"code": "TE16", "name": "Havelock"},
    "OTT": {"code": "TE17", "name": "Outram Park"},
    "MAX": {"code": "TE18", "name": "Maxwell"},
    "SHW": {"code": "TE19", "name": "Shenton Way"},
    "MRE": {"code": "TE20", "name": "Marina Bay"},
    "GRB": {"code": "TE22", "name": "Gardens by the Bay"},
    "TRH": {"code": "TE23", "name": "Tanjong Rhu"},
    "KTP": {"code": "TE24", "name": "Katong Park"},
    "TKT": {"code": "TE25", "name": "Tanjong Katong"},
    "MPR": {"code": "TE26", "name": "Marine Parade"},
    "MTC": {"code": "TE27", "name": "Marine Terrace"},
    "SGL": {"code": "TE28", "name": "Siglap"},
    "BSR": {"code": "TE29", "name": "Bayshore"},
    "BP1": {"code": "BP1", "name": "Choa Chu Kang"},
    "CCB": {"code": "BP1", "name": "Choa Chu Kang"},
    "BP2": {"code": "BP2", "name": "South View"},
    "SHV": {"code": "BP2", "name": "South View"},
    "BP3": {"code": "BP3", "name": "Keat Hong"},
    "KTH": {"code": "BP3", "name": "Keat Hong"},
    "BP4": {"code": "BP4", "name": "Teck Whye"},
    "TKW": {"code": "BP4", "name": "Teck Whye"},
    "BP5": {"code": "BP5", "name": "Phoenix"},
    "PNX": {"code": "BP5", "name": "Phoenix"},
    "BP6": {"code": "BP6", "name": "Bukit Panjang"},
    "BKP": {"code": "BP6", "name": "Bukit Panjang"},
    "BKJ": {"code": "BP6", "name": "Bukit Panjang"},
    "BP7": {"code": "BP7", "name": "Petir"},
    "PTR": {"code": "BP7", "name": "Petir"},
    "BP8": {"code": "BP8", "name": "Pending"},
    "PND": {"code": "BP8", "name": "Pending"},
    "BP9": {"code": "BP9", "name": "Bangkit"},
    "BKT": {"code": "BP9", "name": "Bangkit"},
    "BP10": {"code": "BP10", "name": "Fajar"},
    "FJR": {"code": "BP10", "name": "Fajar"},
    "BP11": {"code": "BP11", "name": "Segar"},
    "SGR": {"code": "BP11", "name": "Segar"},
    "BP12": {"code": "BP12", "name": "Jelapang"},
    "JLP": {"code": "BP12", "name": "Jelapang"},
    "BP13": {"code": "BP13", "name": "Senja"},
    "SNJ": {"code": "BP13", "name": "Senja"},
    "BP14": {"code": "BP14", "name": "Ten Mile Junction"},
    "TMJ": {"code": "BP14", "name": "Ten Mile Junction"},
    "SE1": {"code": "SE1", "name": "Compassvale"},
    "SE2": {"code": "SE2", "name": "Rumbia"},
    "SE3": {"code": "SE3", "name": "Bakau"},
    "SE4": {"code": "SE4", "name": "Kangkar"},
    "SE5": {"code": "SE5", "name": "Ranggung"},
    "SW1": {"code": "SW1", "name": "Cheng Lim"},
    "SW2": {"code": "SW2", "name": "Farmway"},
    "SW3": {"code": "SW3", "name": "Kupang"},
    "SW4": {"code": "SW4", "name": "Thanggam"},
    "SW5": {"code": "SW5", "name": "Fernvale"},
    "SW6": {"code": "SW6", "name": "Layar"},
    "SW7": {"code": "SW7", "name": "Tongkang"},
    "SW8": {"code": "SW8", "name": "Renjong"},
    "PE1": {"code": "PE1", "name": "Cove"},
    "PE2": {"code": "PE2", "name": "Meridian"},
    "PE3": {"code": "PE3", "name": "Coral Edge"},
    "PE4": {"code": "PE4", "name": "Riviera"},
    "PE5": {"code": "PE5", "name": "Kadaloor"},
    "PE6": {"code": "PE6", "name": "Oasis"},
    "PE7": {"code": "PE7", "name": "Damai"},
    "PW1": {"code": "PW1", "name": "Sam Kee"},
    "PW2": {"code": "PW2", "name": "Teck Lee"},
    "PW3": {"code": "PW3", "name": "Punggol Point"},
    "PW4": {"code": "PW4", "name": "Samudera"},
    "PW5": {"code": "PW5", "name": "Nibong"},
    "PW6": {"code": "PW6", "name": "Sumang"},
    "PW7": {"code": "PW7", "name": "Soo Teck"},
  };
}
